LTM.View/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LTM.View.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

LTM.View/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LTM.View.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

LTM.View/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LTM.View.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

LTM.View/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LTM.View.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

LTM.View/Pages/Inicio.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using LTM.View.Classes;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using System.Net;

namespace LTM.View.Pages
{
	public class InicioModel : PageModel
	{
		private Classes.ConexaoAPI _conexaoAPI;

		public InicioModel(Classes.ConexaoAPI conexaoAPI)
		{
			_conexaoAPI = conexaoAPI;
		}
		[BindProperty]
		public bool UsuarioLogado { get; set; }

		public string MensagemErro { get; set; }

		[BindProperty]
		public Entity.API.LoginResponse DadosLogin { get; set; }

		[BindProperty]
		public Logar EfetuarLogin { get; set; }

		[BindProperty]
		public Cadastrar EfetuarCadastro { get; set; }

		public List<Produto> produtos { get; set; }

		[BindProperty]
		public Entity.API.ProdutoAdicionar CadastrarProduto { get; set; }


		public void OnGet()
		{
		}

		public async Task<IActionResult> OnPostLoginAsync()
		{
			this.DadosLogin = _conexaoAPI.Login(new Entity.API.LoginRequest() { Login = EfetuarLogin.Login, Password = EfetuarLogin.Senha });
			if (DadosLogin != null)
			{
				UsuarioLogado = true;
				this.produtos = _conexaoAPI.ListarProdutos(this.DadosLogin.ChaveJwt);
			}
			return Page();
		}

		public async Task<IActionResult> OnPostCadastrarAsync()
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}

			try
			{
				_conexaoAPI.Cadastrar(this.EfetuarCadastro, this.DadosLogin.ChaveJwt);
			}
			catch (WebException ex)
			{
				if (((HttpWebResponse)ex.Response).StatusCode == HttpStatusCode.Unauthorized)
					Erro("Ocorreu um erro de acesso, favor efetue login novamente");
				else
					Erro(ex.Message, true);
			}
			catch (Exception ex)
			{
				Erro(ex.Message, true);
			}

			return Page();
		}

		public async Task<IActionResult> OnPostCadastrarProdutoAsync()
		{
			try
			{
				_conexaoAPI.CadastrarProduto(this.CadastrarProduto, this.DadosLogin.ChaveJwt);
				this.CadastrarProduto = new Entity.API.ProdutoAdicionar();

				this.produtos = _conexaoAPI.ListarProdutos(this.DadosLogin.ChaveJwt);
			}
			catch (WebException ex)
			{
				if (((HttpWebResponse)ex.Response).StatusCode == HttpStatusCode.Unauthorized)
					Erro("Ocorreu um erro de acesso, favor efetue login novamente");
				else
					Erro(ex.Message, true);
			}
			catch (Exception ex)
			{
				Erro(ex.Message, true);
			}
			return Page();
		}

		private void Erro(string erro, bool foiErroAcesso = false)
		{
			DadosLogin = new Entity.API.LoginResponse();
			UsuarioLogado = false;
			produtos = new List<Produto>();
			MensagemErro = erro;
		}
	}
}

LTM.View/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

LTM.View/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LTM.View/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

LTM.View/Pages/Inicio.cshtml
@page
@model InicioModel
@{
}

<script type="text/javascript">
	function ShowLogin() {
		$("#frmLogin").show();
		HiddenCadastrar();
		$("#mainMsgErro").hide();
	}

	function ShowCadastrar() {
		$("#frmCadastrar").show();
		HiddenLogin();
		mainMsgErro
		$("#mainMsgErro").hide();
	}

	function HiddenLogin() {
		$("#frmLogin").hide();
	}

	function HiddenCadastrar() {
		$("#frmCadastrar").hide();
	}

	function ShowCadastrarProduto() {
		$("#frmCadastrarProduto").show();

		$("#inputCadastroProdutoNome").val("");
		$("#inputCadastroProdutoDescricao").val("");
		$("#inputCadastroProdutoEspecificacoes").val("");
		$("#inputCadastroProdutoItensEstoque").val("");
	}
</script>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
	@if (Model.UsuarioLogado)
	{
		<label class="navbar-brand">@Model.DadosLogin.Nome</label>
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="btn btn-outline-success my-2 my-sm-0 nav-link " onclick="ShowCadastrarProduto()">Cadastrar Produto</a>
			</li>
		</ul>
	}
	else
	{
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" onclick="ShowLogin()">Login</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" onclick="ShowCadastrar()">Cadastro</a>
				</li>
			</ul>
		</div>
	}
</nav>

@if (!string.IsNullOrEmpty(Model.MensagemErro))
{
	<main role="main" id="mainMsgErro" class="container">
		<section class="jumbotron text-center">
			<h2>@Model.MensagemErro</h2>
		</section>
	</main>
}

<main role="main" class="container">
	<form id="frmLogin" style="display:none" method="post">
		<section class="jumbotron text-center">
			<div class="container col-md-4">
				<h2 class="form-signin-heading">Dados de Login</h2>
				<input type="text" id="inputLogin" asp-for="EfetuarLogin.Login" class="form-control margin10" placeholder="Login" required="" autofocus="">
				<input type="password" asp-for="EfetuarLogin.Senha" id="inputPassword" class="form-control margin10" placeholder="Senha" required="">
				<button class="btn btn-lg btn-primary btn-block margin10" asp-page-handler="Login" type="submit">Login</button>
			</div>
		</section>
	</form>


	<form id="frmCadastrar" style="display:none" method="post">
		<section class="jumbotron text-center">
			<div class="container col-md-4">
				<h2 class="form-signin-heading">Dados para Cadastro</h2>
				<input type="text" id="inputCadastroNome" asp-for="EfetuarCadastro.Nome" class="form-control margin10" placeholder="Nome" required="" autofocus="">
				<input type="email" id="inputCadastroEmail" asp-for="EfetuarCadastro.Email" class="form-control margin10" placeholder="Email" required="" autofocus="">
				<input type="text" id="inputCadastroLogin" asp-for="EfetuarCadastro.Login" class="form-control margin10" placeholder="Login" required="" autofocus="">
				<input type="password" id="inputCadastroPassword" asp-for="EfetuarCadastro.Senha" class="form-control margin10" placeholder="Senha" required="">
				<button class="btn btn-lg btn-primary btn-block margin10" asp-page-handler="Cadastrar" type="submit">Cadastrar</button>
			</div>
		</section>
	</form>
	@if (Model.UsuarioLogado)
	{
		<form id="frmCadastrarProduto" style="display:none" asp-antiforgery="true" method="post">
			<section class="jumbotron text-center">
				<div class="container col-md-4">
					<h2 class="form-signin-heading">Dados para Cadastro de Produto</h2>
					<input type="text" id="inputCadastroProdutoNome" asp-for="CadastrarProduto.Nome" class="form-control margin10" placeholder="Nome" required="" autofocus="">
					<input type="text" id="inputCadastroProdutoDescricao" asp-for="CadastrarProduto.Descricao" class="form-control margin10" placeholder="Descricao" required="" autofocus="">
					<input type="text" id="inputCadastroProdutoEspecificacoes" asp-for="CadastrarProduto.Especificacoes" class="form-control margin10" placeholder="Especificacoes" required="" autofocus="">
					<input type="number" id="inputCadastroProdutoItensEstoque" asp-for="CadastrarProduto.ItensEstoque" class="form-control margin10" placeholder="ItensEstoque" required="">
					<button class="btn btn-lg btn-primary btn-block margin10" asp-page-handler="CadastrarProduto" type="submit">Cadastrar Produto</button>
					<input type="hidden" id="dadosLogin1" asp-for="DadosLogin.Id" />
					<input type="hidden" id="dadosLogin2" asp-for="DadosLogin.Login" />
					<input type="hidden" id="dadosLogin3" asp-for="DadosLogin.Nome" />
					<input type="hidden" id="dadosLogin4" asp-for="DadosLogin.ChaveJwt" />
					<input type="hidden" id="dadosLogin5" asp-for="DadosLogin.Email" />
					<input type="hidden" id="dadosLogin6" asp-for="UsuarioLogado" />
				</div>
			</section>
		</form>

		@if (Model.produtos != null)
		{
			<form>
				<div class="jumbotron">
					<div class="container">
						<div class="row">
							@foreach (var item in Model.produtos)
							{
								<div class="card col-md-5" style="margin:5px">
									Nome: @item.Nome
									<br />
									Descrição: @item.Descricao
									<br />
									Especificações: @item.Especificacao
									<br />
									Estoque: @item.QuantidadeEstoque
								</div>
							}
						</div>
					</div>
				</div>
			</form>
		}
	}
</main>

LTM.View/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>


	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	<style>
		.margin10 {
			margin-top: 10px;
		}
	</style>


    @*<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LTM.View</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>*@
</head>
<body>
    @*<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">LTM.View</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">*@
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; 2017 - LTM.View</p>
        </footer>
    </div>*@

    @*<environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>*@

    @RenderSection("Scripts", required: false)
</body>
</html>